### PR TITLE
Fix fps drops from image processing work on main thread

### PR DESCRIPTION
**Pull request by metinn**
Hi, thank you for the library!

I recently used it to display multiple GIF's in grid. I had some performance issue due to main thread load. I used async feature to prevent fps drops, by moving image processing work from main thread to background thread

### CODE REVIEW

**Comment by gordan-glavas-codecons** [comment]
Hi, thanks for contributing! The issue with the proposed solution is that async/await can only run on iOS 15, meaning that we'd have to drop support for iOS 13 & 14. We should rework it so that there are two sets of methods, a sync and an async one, with async ones wrapped in conditional pre-processing directives that run only if iOS 15 or above is available.

**Comment by metinn** [comment]
Good point. To keep it simple I can change the Task with DispatchQueue global and main. What do you think ?

**Comment by gordan-glavas-codecons** [comment]
You can give it a go, if it works it's a viable solution.

**Comment by metinn** [comment]
What do you think about the change to DispatchQueue ?

**Comment by gordan-glavas-codecons** [comment]
Sorry, I didn't have time to test it until today. It looks and works well, merging.

**Pull request merged**
